### ISSUE TITLE
Code not working, getting error when saving pdf

### ISSUE THREAD

**Issue by chandraS76** [realChesta/slide-extractor#2]
progress: ~94% @ 172 fps | about 0h 0min 21s left
progress: ~95% @ 171 fps | about 0h 0min 17s left
progress: ~96% @ 171 fps | about 0h 0min 13s left
progress: ~99% @ 170 fps | about 0h 0min 4s left
Saving PDF...
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main.start()
  File "main.py", line 103, in start
    self.convertToPDF()
    f.write(img2pdf.convert(imgs))
  File "C:\Users\Chandrasang\Anaconda3\lib\site-packages\img2pdf.py", line 2084, in convert
    return pdf.tostring()
  File "C:\Users\Chandrasang\Anaconda3\lib\site-packages\img2pdf.py", line 955, in tostring
    self.tostream(stream)
  File "C:\Users\Chandrasang\Anaconda3\lib\site-packages\img2pdf.py", line 1049, in tostream
    initial_page = self.writer.pages[0]
IndexError: Accessing nonexistent PDF page number

i get this error everytime.

**Comment by realChesta** [comment]
Hi, would you mind providing more context? 

- What kind of file are you trying to process?
- Where are you trying to save it to?
- What version of img2pdf are you using?

**Comment by chandraS76** [comment]
Hey

1. Im trying to process a google meet recording, of type mp4.
2. I haven't modified the save, it's set to default
3. I have first used the specified version of img2pdf, then updated to the latest version but still, it gives the same error.

**Comment by xXgordonXx** [comment]
Hi @chandraS76 , seems the program could not detect and extract any slides from the video. As a new slide is detected, it will print a message "Found a new slide!". I have the same issue before. I found out that it might be due to the onTrigger function in main.py
    def onTrigger(self, frame):
        frame = self.cropImage(frame)

        # if frame is not None and self.checkRatio(frame, 1.2, 1.5): 
        # remove the self.checkRatio(frame, 1.2, 1.5) as the size of frame might be larger than 1.5, mine are 1.88, so i amend this part of code        

        if frame is not None :
            if self.dupeHandler.check(frame):
                print("Found a new slide!")
            # self.saveSlide(frame)

**Comment by aksamiftikhar** [comment]
Yes, it's working after applying this solution. 
Many Thanks !!!!!

> Hi @chandraS76 , seems the program could not detect and extract any slides from the video. As a new slide is detected, it will print a message "Found a new slide!". I have the same issue before. I found out that it might be due to the onTrigger function in main.py def onTrigger(self, frame): frame = self.cropImage(frame)
> 
> ```
>     # if frame is not None and self.checkRatio(frame, 1.2, 1.5): 
>     # remove the self.checkRatio(frame, 1.2, 1.5) as the size of frame might be larger than 1.5, mine are 1.88, so i amend this part of code        
> 
>     if frame is not None :
>         if self.dupeHandler.check(frame):
>             print("Found a new slide!")
>         # self.saveSlide(frame)
> ```
